# @package _global_
defaults:
  - override /scheduler: linear_with_warmup
  - override /model: fairr_ruleselector_roberta
  - override /setup: rtx_8000_b32_a1

seed: 42
max_epochs: 15
learning_rate: 1e-6
save_checkpoint: True
adam_epsilon: 1e-6
weight_decay: 0.01
